INSERT INTO burgerseqs (burger_name) VALUES ('The Mayflower');
INSERT INTO burgerseqs (burger_name) VALUES ('Classic Burger');
INSERT INTO burgerseqs (burger_name) VALUES ('Goodnight/Good Cause');
INSERT INTO burgerseqs (burger_name, devoured) VALUES ('Magic Shroom', true);
INSERT INTO burgerseqs (burger_name, devoured) VALUES ('Llano Poblano', true);
INSERT INTO burgerseqs (burger_name, devoured) VALUES ('El Diablo', true);
INSERT INTO burgerseqs (burger_name) VALUES ('Buffalo Bill');
INSERT INTO burgerseqs (burger_name) VALUES ('Primetime');
INSERT INTO burgerseqs (burger_name) VALUES ('Thunderbird');
INSERT INTO burgerseqs (burger_name) VALUES ('The Impossible');
INSERT INTO burgerseqs (burger_name) VALUES ('Terlingua');
